### ISSUE TITLE
Unknown template resource: AWSEBLoadBalancer

### ISSUE THREAD

**Issue by Fir3Chi3f** [awslabs/eb-php-wordpress#5]
[Following this tutorial](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/php-hawordpress-tutorial.html#php-hawordpress-tutorial-updateenv)

In the Launch an Elastic Beanstalk Environment section I keep getting this error after uploading and attempting to deploy
> Unknown template resource: AWSEBLoadBalancer

**Comment by mwunderl** [comment]
Hi Fir3Chi3f,
Your environment is missing a load balancer. Try adding one with the instructions here:
[Changing Environment Type](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-types.html?shortFooter=true#using-features.managing.changetype)

Thanks,
-Michael

**Comment by canfone** [comment]
Hello ~

I am trying to create an eb application using eb cli with Multiple Docker Container. I have an applications running on 2 ports so I need to listen on those ports. I tried your configuration on your `.ebextensions/elb-listeners.config`  but I encounter an error of `ERROR: Service:AmazonCloudFormation, Message:Template error: instance of Fn::GetAtt references undefined resource AWSEBLoadBalancer`. Below is my configuration.

```
option_settings:
  aws:elb:listener:8745:
    ListenerProtocol: HTTP
    InstanceProtocol: HTTP
    InstancePort: 8745
  aws:elb:listener:3517:
    ListenerProtocol: HTTP
    InstanceProtocol: HTTP
    InstancePort: 3517

Resources:
  port8745SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupName: {Ref : AWSEBSecurityGroup}
      IpProtocol: tcp
      ToPort: 8745
      FromPort: 8745
      SourceSecurityGroupName: { "Fn::GetAtt": ["AWSEBLoadBalancer", "SourceSecurityGroup.GroupName"] }
      SourceSecurityGroupOwnerId: { "Fn::GetAtt": ["AWSEBLoadBalancer", "SourceSecurityGroup.OwnerAlias"] }
  port3517SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupName: {Ref : AWSEBSecurityGroup}
      IpProtocol: tcp
      ToPort: 3517
      FromPort: 3517
      SourceSecurityGroupName: { "Fn::GetAtt": ["AWSEBLoadBalancer", "SourceSecurityGroup.GroupName"] }
      SourceSecurityGroupOwnerId: { "Fn::GetAtt": ["AWSEBLoadBalancer", "SourceSecurityGroup.OwnerAlias"] }
```

Do you know where did I miss? I'm a newbie in AWS so sorry for my ignorance. Your help will be much appreciated.

Thanks!
